# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'QNTZ-swift4.0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Networking
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Alamofire-SwiftyJSON'
  pod 'Moya'


  # UI
  pod 'SnapKit'
  pod 'UIView+Positioning'
  pod 'IQKeyboardManagerSwift'
  pod 'PullToRefreshKit'
  pod 'PKHUD' # loading
  pod 'SwiftMessages' # 文字提示
  pod 'SKPhotoBrowser' # 图片浏览器
  pod 'GrowingTextView' # 自动改变大小TextView
  pod 'FSPagerView' #  Banner View、Product Show、Welcome/Guide Pages、Screen/ViewController Sliders
  
  pod 'JZNavigationExtension' # 右滑返回，改变导航栏状态
  pod 'KVOController'
 
  pod 'Device'
  
#  pod 'GRDB.swift'
  pod 'WCDB.swift'

  # Pods for QNTZ-swift4.0

  target 'QNTZ-swift4.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QNTZ-swift4.0UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
